name: Deploy API to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/cloud-run-deploy.yml"

concurrency:
  group: cloud-run-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
      SERVICE_DIR: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # For first pass, use a JSON key. Later migrate to WIF/OIDC.
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # How does it know that it should use the server folder here?
      - name: Deploy to Cloud Run from source
        run: |
          gcloud run deploy "$SERVICE" \
            --source "$SERVICE_DIR" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated
